# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

###########################
#### Gradle properties ####
#########################
group=me.srrrapero720

#########################
#### Mod properties ####
#######################
modid=chloride
modname=Chloride
modversion=1.7.0
modauthor=SrRapero720
modcredits=none
moddesc=Makes sodium a tasteful experience
modlicense=All-Rights-Reserved
github=SrRapero720/chloride
modpackformat=15

#####################
#### Enviroment ####
###################
javaversion=17
modloader=FORGE
modloader_short=FG
mcversion=1.20.1
minecraftrange=[1.20.1,1.20.2)
forgeversion=47.4.0
forgerange=[47.4.0,)
fmlrange=[47,48)
mappingschannel=parchment
mappingsversion=2023.09.03-1.20.1

curseforgeid=931925
modrinthid=yD9qW65f
versiontype=release

#######################
#### Dependencies ####
#####################
sodiumversion=5681725
sodiumrange=[0,)

irisversion=6020952
irisrange=[0,)

# JREMI SUPORT
jeiversion=6075247
emiversion=5096955
reiversion=5846923
archversion=5137938
clothversion=5729105

#######################
#### Mixins config ###
#####################
mixin_version=0.8.5
mixin_fabric_version=0.12.5
mixinextra_version=0.3.5
mixinextra_version_range=[0.3.5,)
mixin_file_suffix=mixin.json
mixin_refmap_suffix=mixin-refmap.json

#################
#### Others ####
###############
createversion=6.0.1-23
flywheelversion=1.0.1-221
ponderversion=1.0.39
registrateversion=MC1.20-1.3.3