pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
    // PLUGIN VERSIONS LIVE IN gradle.properties; build.gradle APPLIES THEM VERSION-LESS
    plugins {
        id 'org.gradle.toolchains.foojay-resolver-convention' version foojayversion
        id 'net.minecraftforge.gradle' version forgegradleversion
        id 'net.minecraftforge.renamer' version renamerversion
        id 'me.modmuss50.mod-publish-plugin' version publishpluginversion
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention'
}

rootProject.name = modid
