modLoader="javafml" #mandatory
loaderVersion="${fmlrange}"
license="${modlicense}"
issueTrackerURL="https://github.com/${github}/issues"

[[mixins]]
    config="$modid.$mixin_file_suffix"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mods]]
    modId="${modid}"
    version="${modversion}"
    displayName="${modname}"
    type="required"
    logoFile="pack.png" #optional
    authors="${modauthor}" #optional
    credits="${modcredits}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/${modid}"
    description='''${moddesc}'''

[[dependencies.${modid}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraftrange}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="sodium"
    type="required"
    versionRange="${sodiumrange}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="smoothskies"
    type="incompatible"
    reason="Chloride ships every Smooth Skies feature natively."
    versionRange="[0,)"
    ordering="NONE"
    side="CLIENT"